# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 940d455640ac1b29e57e29519bac9eea7d1f3489f12580a275aa7f1a6f568016ee31f9ad874918f242210e8a8cbeb8e0a889ca777dd9f128a2ffce7add605fd5

test:
  secret_key_base: 3e58e129194a927155c2e97ce1a96d30b78ab672488fa954e3bc2715b96230f05b2f110229fe7c8c46b2144fd89a8243a1cb288183b4dd0ccf3c5d954f0bdca9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
